services:
  grpcapp:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: grpcapp
    ports:
      - "9092:9092"
    volumes:
      - ./logs:/app/logs
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - "5173:5173"
    volumes:
      - ./web-client:/app
      - /app/node_modules
    depends_on:
      - grpcapp
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: climatechart
    volumes:
      - mongo_data:/data/db
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: envoy
    depends_on:
      - grpcapp
    ports:
      - "8089:8089"
      - "9099:9099"
    volumes:
      - ./envoy/envoy_grpc_to_json.yaml:/etc/envoy/envoy.yaml:ro
      - ./apis.pb:/data/apis.pb:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]

volumes:
  mongo_data:

